repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: pflake8
        name: pflake8
        stages: [commit]
        language: system
        entry: poetry run pflake8
        types: [python]
        exclude: setup.py

      - id: gitlint
        name: gitlint
        stages: [commit-msg]
        language: system
        entry: poetry run gitlint
        args:
          - "--staged"
          - "--msg-filename"

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy .
        types: [python]
        pass_filenames: false


      - id: toml-sort
        name: toml-sort
        stages: [commit]
        language: system
        entry: poetry run toml-sort
        pass_filenames: False
        files: pyproject.toml
